# Generated by Django 2.0.2 on 2018-03-09 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bug',
            old_name='fiexed',
            new_name='fixed',
        ),
    ]
